### ISSUE TITLE
GitHub checks aren't created when using a Personal Access Token

### ISSUE THREAD

**Issue by emma-sax4** [gr2m/merge-schedule-action#10]
One thing I've unfortunately noticed is that using this workflow to merge a pull request doesn't trigger any other workflow to run (I have another workflow that runs on `push` to my default branch). I should be able to get around this by using a Personal Access Token to authenticate instead of the `${{ secrets.GITHUB_TOKEN }}`.

But when I use a Personal Access Token instead of the normal `GITHUB_TOKEN`, I get this complaint:
![image](https://user-images.githubusercontent.com/7562793/82129052-a43b0f80-9785-11ea-8c2e-3aadeb0498ce.png)

I know this has something to do specifically with creating the new GitHub PR checks which eventually do the merging itself.

I've deducted that to create a GitHub check, I need to be authenticated as a GitHub app. But for some reason, using a Personal Access Token instead of `GITHUB_TOKEN` doesn't authenticate the GitHub app, like it does normally.

In the meantime, I have two workflows set up. One of them runs on PR updates, and is responsible for creating the PR status checks and is given the `${{ secrets.GITHUB_TOKEN }}`, and the other is responsible for actually merging and is given the `${{ secrets.PERSONAL_ACCESS_TOKEN }}`. But it's not the solution I'd preferably want.

Any help figuring this out would be greatly appreciated.

**Comment by gr2m** [comment]
In order to create a check run you will need to authenticate as a GitHub App installation. You will need 

1. The App ID
2. A Private key `*.pem` file contents
3. Installation ID

Here is a script I run in a GitHub Action:
https://github.com/octokit/routes/blob/master/bin/notify-users.js

What you could do is generate an installation access token and then dynamically set an environment variable before running the merge action, then use that environment variable to set the `env.GITHUB_TOKEN`.

See https://github.com/actions/toolkit/tree/master/packages/core#exporting-variables. I never used that myself, but it should work :tm:

**Comment by emma-sax4** [comment]
Yes, I had an inkling feeling that there'd be a lot of changes involved to get it to work properly with the `PERSONAL_ACCESS_TOKEN`, but thought I'd bring it up in case it was an easy change.

Thanks for getting back to me.
