### ISSUE TITLE
Cannot read property 'owner' of undefined when merging PR

### ISSUE THREAD

**Issue by jerriep** [gr2m/merge-schedule-action#33]
I scheduled a PR to be merged at a specific date. At the appointed time, my GH Action ran and the PR was merged successfully. Even though the PR was merged, the action failed due to an error in the `merge-schedule-action` action.

You can see the log from my action below.

```
Run gr2m/merge-schedule-action@v1.x
  with:
    merge_method: merge
    time_zone: UTC
  env:
    GITHUB_TOKEN: ***
Loading open pull request
2 scheduled pull requests found
1 due pull requests found
Warning: Unhandled Rejection at:
Warning: {}
Error: TypeError: Cannot read property 'owner' of undefined
```

Due to the fact that the PR was merged, I suspect this is related to the lines of code that update the checks:
https://github.com/gr2m/merge-schedule-action/blob/ee997a26b85a0c86189ff1fc31d30f12c3729bc3/lib/handle_schedule.js#L66-L86

**Comment by panduit-bilb** [comment]
Any plans at work to resolve this issue?

**Comment by gr2m** [comment]
Pull request welcome! I cannot work on it myself anytime soon, but happy to review a PR

**Comment by pepopowitz** [comment]
I've done a bit of research and my theory at this point is that the payload for `on:schedule` actions doesn't have all the meta info that [the docs would lead you to believe they have](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#webhook-payload-object-common-properties).

Here's a failed run (I _think_ you can see this even if you're not me) with some logging of the payload: https://github.com/pepopowitz/stevenhicks.me/runs/2015250341?check_suite_focus=true

The payload:
```
payload: {
  "schedule": "*/5 * * * MON-FRI"
}
```

Hence the failures on `eventPayload.repository.(anything)`. 

I'm very curious to hear if others experiencing this problem are seeing it on scheduled actions, like me.

## How do we fix this?

We're looking for the owner.login and repo.name so that we can close out the check that we opened when we found this scheduled PR. 

- Maybe we can get them from somewhere else if they're not in the payload?
- Maybe we just give up if they're not in the payload?

I'm guessing the repo name we get [at the top of `handle_schedule.js`](https://github.com/gr2m/merge-schedule-action/blob/ee997a26b85a0c86189ff1fc31d30f12c3729bc3/lib/handle_schedule.js#L12) is the one we're looking for. My next step will be to research if we can get the `owner.login` from somewhere else, too.

## How did I identify this?

I didn't really know how to do any of this, so I'm sharing it here in case it's new to others.
1. I forked, created a branch, & [added some more logging](https://github.com/pepopowitz/merge-schedule-action/commit/869cee44698f54bc51396dd8f8cfef1dd2d9b224#diff-60a9453719d4435584e5cab338bc14b547c9bb4bfcbf22dafec62476ddc1ede5R65) to this action
2. I [pointed my action](https://github.com/pepopowitz/stevenhicks.me/commit/e9d50a8a7abb106b2d903fd4d302e9292346cb2d) at my fork/branch version. 
3. I re-ran actions to see the additional logging.

**Comment by gr2m** [comment]
I think you are right, #34 should fix it
