### ISSUE TITLE
Post a comment with an explenation when a pull request cannot be merged on schedule

### ISSUE THREAD

**Issue by lloydjatkinson** [gr2m/merge-schedule-action#67]
Hi, I really like the look of this action, thanks for making it! Just wondering what happens in the case that a merge conflict arises?

**Comment by gr2m** [comment]
The pull request won't be merged.

Now that we use comments, I wonder if we should post a comment if the merge time passed and the pull request cannot be merged? @ruisaraiva19

**Comment by ruisaraiva19** [comment]
> The pull request won't be merged.
> 
> Now that we use comments, I wonder if we should post a comment if the merge time passed and the pull request cannot be merged? @ruisaraiva19 

Yes, we can definitely post a comment with a contextualized message :wink:

**Comment by gr2m** [comment]
great, I updated the issue title accordingly 👍🏼

**Comment by ruisaraiva19** [comment]
@gr2m  Can we reuse the same comment that we already have or should we just create a new one for this scenario?

**Comment by gr2m** [comment]
I'd say post a new one, that will trigger a notification. Updating an existing comment does not. 

But just like with the other, only post the comment once. I wonder if we should also add a label such as `automerge-fail` and not try again when the label is set. We could say in the comment that in order to let the automerge-automation try again, the label should be removed.
