### ISSUE TITLE
Netlify still runs deploy attempt and fails

### ISSUE THREAD

**Issue by RobertMyles** [gr2m/merge-schedule-action#8]
Hi,
Thanks for the great Action, really useful!

I'm using it to post blog posts on a future date, as described [here](https://www.jerriepelser.com/blog/schedule-posts-gatsby-netlify/). However, it fails initially, as Netlify complains that there is a lingering process. Here is the relevant snippet of the Netlify log:

```
5:50:43 PM: ** WARNING **
5:50:43 PM: There are some lingering processes even after the build process finished:
5:50:43 PM: USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
5:50:43 PM: buildbot    3409  7.0  0.7 775188 223048 ?       Rl   17:49   0:07 /opt/buildhome/.nvm/versions/node/v10.19.0/bin/node /opt/build/repo/node_modules/jest-worker/build/workers/processChild.js
5:50:43 PM: Our builds do not kill your processes automatically, so please make sure
5:50:43 PM: that nothing is running after your build finishes, or it will be marked as
5:50:43 PM: failed since something is still running.
```

Here is my PR where all of this is happening: https://github.com/RobertMyles/site/pull/3 

Am I using the Action correctly? How can I get these checks to pass, or is this something that needs to be done on the Netlify side?

Thanks for your help,
Robert

**Comment by gr2m** [comment]
Hi Robert, glad to hear that you find the action useful! I love your blog post!

I don't know what this could be 🤔 but I don't think it relates to this action. The error message includes [`jest-worker`](https://www.npmjs.com/package/jest-worker) which seems to be part of Facebooks `jest` test framework. Are you using jest for any tests yourself? 

Note that things might also be broken right now because GitHub itself is experiencing elevated error rates: https://www.githubstatus.com/.

Did it work at some point?

**Comment by RobertMyles** [comment]
Hi Gregor, 
I'm using Gatsby, so I'm not explicitly using jest, maybe it's something that's running under the hood or with some other package. Ok, happy to hear I'm using the Action correctly 😄

Thanks, I'll close this now.
